### ISSUE TITLE
Automated build

### ISSUE THREAD

**Issue by Razdeep** [Razdeep/Competitive-Programming-Starters-Kit#3]
Use **GitHub Actions** to pull and build the code.
Perform unit tests on the generated executable.
Add build badges to _README_

**Comment by lordgamez** [comment]
Hi, happy Hacktoberfest! Added PR #4 with automated build. You can check the results [here](https://github.com/lordgamez/Competitive-Programming-Starters-Kit/actions/runs/289798219)

**Comment by lordgamez** [comment]
If you are okay with the PR would you please add the "hacktoberfest" topic to their repository "hacktoberfest-accepted" label to the PR to be eligible for Hacktoberfest? Unfortunately the rules have changed a few days ago.

**Comment by Razdeep** [comment]
I have reviewed your PR and added the appropriate labels. Thanks for contributing.
